apiVersion: v1 
kind: Service 
metadata: 
  name: mysql-service 
  namespace: roboshop
  labels:
    app: mysql 
    project: roboshop 
    tier: db 
spec:
  clusterIP: None 
  selector:
    matchLabels:
      app: mysql 
      project: roboshop 
      tier: db 
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

