apiVersion: v1 
kind: Service 
metadata: 
  name: redis-service 
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db 
spec:
  clusterIP: None 
  selector:
    matchLabels:
      app: redis 
      project: roboshop
      tier: db 
  ports:
  - protocol: TCP 
    port: 6379
    targetPort: 6379